### PR TITLE
Add sync-timestamp filter to use first topic

### PR DESCRIPTION
**Pull request by wallner90**
Added option to unify all written files to use the timestamp of the first given topic.

### CODE REVIEW

**Comment by devrite** [comment]
@wallner90 Just recalled that we need to check the order of topics. The synchronization filters are created as a dict (topic: filter) and whatever order comes out of it will be the order of the message, which may conflict with the order on the command line.

**Comment by devrite** [comment]
@Kettenhoax LGTM!

**Review by Kettenhoax — CHANGES_REQUESTED** [review]
Looks good overall! I've requested some changes inline.

**Comment by wallner90** [comment]
Still one change open.

**Comment by wallner90** [comment]
Done!

**Comment by Kettenhoax** [comment]
LGTM!

**Pull request merged**
